# Generated by Django 4.2.6 on 2023-10-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyussh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-time_create'], name='dyussh_news_time_cr_c03b50_idx'),
        ),
    ]
