# Generated by Django 4.2.6 on 2023-11-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyussh', '0003_alter_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='news_sport_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dyussh.newssporttype'),
        ),
    ]
