# Generated by Django 4.2.6 on 2023-11-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyussh', '0004_newssporttype_alter_news_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dyussh.newssporttype'),
        ),
    ]
