# Generated by Django 4.2.6 on 2023-11-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyussh', '0005_alter_news_news_sport_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
    ]
